#!/bin/bash

qmake -project

sed -i 's/^TARGET = .*/TARGET = MinecraftModManager/' QtMinecraft.pro
sed -i "7a QT += widgets gui core xml" QtMinecraft.pro

mkdir -p build/obj build/moc build/ui

echo "OBJECTS_DIR = build/obj" >> QtMinecraft.pro
echo "MOC_DIR = build/moc" >> QtMinecraft.pro

qmake

make
#if [ $? -eq 0 ]; then
#    clear
#fi
