#############################################################################
# Makefile for building: MinecraftModManager
# Generated by qmake (3.1) (Qt 6.4.2)
# Project:  CompilerMinecraftQt.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile CompilerMinecraftQt.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I. -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtXml -I/usr/include/x86_64-linux-gnu/qt6/QtCore -Ibuild/moc -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MinecraftModManager1.0.0
DISTDIR = /home/astrubale/Progetti/CompilerMinecraftQt/build/obj/MinecraftModManager1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt6Widgets.so /usr/lib/x86_64-linux-gnu/libQt6Gui.so /usr/lib/x86_64-linux-gnu/libGLX.so /usr/lib/x86_64-linux-gnu/libOpenGL.so /usr/lib/x86_64-linux-gnu/libQt6Xml.so /usr/lib/x86_64-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = src/main.cpp \
		src/logic/Block.cpp \
		src/logic/Item.cpp \
		src/logic/JsonHandler.cpp \
		src/logic/JsonVisitor.cpp \
		src/logic/LibraryManager.cpp \
		src/logic/LightBlock.cpp \
		src/logic/Material.cpp \
		src/logic/MinecraftObj.cpp \
		src/logic/ObjectFactory.cpp \
		src/logic/OreBlock.cpp \
		src/logic/Weapon.cpp \
		src/logic/XmlHandler.cpp \
		src/logic/XmlVisitor.cpp \
		src/ui/CardVisitor.cpp \
		src/ui/FormVisitor.cpp \
		src/ui/ListView.cpp \
		src/ui/MainWindow.cpp \
		src/ui/TypeSelectionDialog.cpp build/moc/moc_FormVisitor.cpp \
		build/moc/moc_ListView.cpp \
		build/moc/moc_MainWindow.cpp \
		build/moc/moc_TypeSelectionDialog.cpp
OBJECTS       = build/obj/main.o \
		build/obj/Block.o \
		build/obj/Item.o \
		build/obj/JsonHandler.o \
		build/obj/JsonVisitor.o \
		build/obj/LibraryManager.o \
		build/obj/LightBlock.o \
		build/obj/Material.o \
		build/obj/MinecraftObj.o \
		build/obj/ObjectFactory.o \
		build/obj/OreBlock.o \
		build/obj/Weapon.o \
		build/obj/XmlHandler.o \
		build/obj/XmlVisitor.o \
		build/obj/CardVisitor.o \
		build/obj/FormVisitor.o \
		build/obj/ListView.o \
		build/obj/MainWindow.o \
		build/obj/TypeSelectionDialog.o \
		build/obj/moc_FormVisitor.o \
		build/obj/moc_ListView.o \
		build/obj/moc_MainWindow.o \
		build/obj/moc_TypeSelectionDialog.o
DIST          = /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		CompilerMinecraftQt.pro src/logic/Block.h \
		src/logic/Item.h \
		src/logic/JsonHandler.h \
		src/logic/JsonVisitor.h \
		src/logic/LibraryManager.h \
		src/logic/LightBlock.h \
		src/logic/Material.h \
		src/logic/MinecraftObj.h \
		src/logic/MinecraftObjManager.h \
		src/logic/MinecraftObjVisitor.h \
		src/logic/ObjectFactory.h \
		src/logic/OreBlock.h \
		src/logic/Weapon.h \
		src/logic/XmlHandler.h \
		src/logic/XmlVisitor.h \
		src/ui/CardVisitor.h \
		src/ui/FormVisitor.h \
		src/ui/ListView.h \
		src/ui/MainWindow.h \
		src/ui/TypeSelectionDialog.h src/main.cpp \
		src/logic/Block.cpp \
		src/logic/Item.cpp \
		src/logic/JsonHandler.cpp \
		src/logic/JsonVisitor.cpp \
		src/logic/LibraryManager.cpp \
		src/logic/LightBlock.cpp \
		src/logic/Material.cpp \
		src/logic/MinecraftObj.cpp \
		src/logic/ObjectFactory.cpp \
		src/logic/OreBlock.cpp \
		src/logic/Weapon.cpp \
		src/logic/XmlHandler.cpp \
		src/logic/XmlVisitor.cpp \
		src/ui/CardVisitor.cpp \
		src/ui/FormVisitor.cpp \
		src/ui/ListView.cpp \
		src/ui/MainWindow.cpp \
		src/ui/TypeSelectionDialog.cpp
QMAKE_TARGET  = MinecraftModManager
DESTDIR       = 
TARGET        = MinecraftModManager


first: all
####### Build rules

MinecraftModManager:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CompilerMinecraftQt.pro /usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		CompilerMinecraftQt.pro \
		/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Xml.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Core.prl
	$(QMAKE) -o Makefile CompilerMinecraftQt.pro
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf:
CompilerMinecraftQt.pro:
/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt6Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt6Xml.prl:
/usr/lib/x86_64-linux-gnu/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile CompilerMinecraftQt.pro

qmake_all: FORCE


all: Makefile MinecraftModManager

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/logic/Block.h src/logic/Item.h src/logic/JsonHandler.h src/logic/JsonVisitor.h src/logic/LibraryManager.h src/logic/LightBlock.h src/logic/Material.h src/logic/MinecraftObj.h src/logic/MinecraftObjManager.h src/logic/MinecraftObjVisitor.h src/logic/ObjectFactory.h src/logic/OreBlock.h src/logic/Weapon.h src/logic/XmlHandler.h src/logic/XmlVisitor.h src/ui/CardVisitor.h src/ui/FormVisitor.h src/ui/ListView.h src/ui/MainWindow.h src/ui/TypeSelectionDialog.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/logic/Block.cpp src/logic/Item.cpp src/logic/JsonHandler.cpp src/logic/JsonVisitor.cpp src/logic/LibraryManager.cpp src/logic/LightBlock.cpp src/logic/Material.cpp src/logic/MinecraftObj.cpp src/logic/ObjectFactory.cpp src/logic/OreBlock.cpp src/logic/Weapon.cpp src/logic/XmlHandler.cpp src/logic/XmlVisitor.cpp src/ui/CardVisitor.cpp src/ui/FormVisitor.cpp src/ui/ListView.cpp src/ui/MainWindow.cpp src/ui/TypeSelectionDialog.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: build/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc/moc_predefs.h
build/moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -fPIC -dM -E -o build/moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc/moc_FormVisitor.cpp build/moc/moc_ListView.cpp build/moc/moc_MainWindow.cpp build/moc/moc_TypeSelectionDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_FormVisitor.cpp build/moc/moc_ListView.cpp build/moc/moc_MainWindow.cpp build/moc/moc_TypeSelectionDialog.cpp
build/moc/moc_FormVisitor.cpp: src/ui/FormVisitor.h \
		src/logic/MinecraftObjVisitor.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/astrubale/Progetti/CompilerMinecraftQt/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/astrubale/Progetti/CompilerMinecraftQt -I/home/astrubale/Progetti/CompilerMinecraftQt -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtXml -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ui/FormVisitor.h -o build/moc/moc_FormVisitor.cpp

build/moc/moc_ListView.cpp: src/ui/ListView.h \
		src/logic/MinecraftObj.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/astrubale/Progetti/CompilerMinecraftQt/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/astrubale/Progetti/CompilerMinecraftQt -I/home/astrubale/Progetti/CompilerMinecraftQt -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtXml -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ui/ListView.h -o build/moc/moc_ListView.cpp

build/moc/moc_MainWindow.cpp: src/ui/MainWindow.h \
		src/ui/ListView.h \
		src/logic/MinecraftObj.h \
		src/ui/FormVisitor.h \
		src/logic/MinecraftObjVisitor.h \
		src/logic/LibraryManager.h \
		src/logic/Material.h \
		src/logic/Item.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/astrubale/Progetti/CompilerMinecraftQt/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/astrubale/Progetti/CompilerMinecraftQt -I/home/astrubale/Progetti/CompilerMinecraftQt -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtXml -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ui/MainWindow.h -o build/moc/moc_MainWindow.cpp

build/moc/moc_TypeSelectionDialog.cpp: src/ui/TypeSelectionDialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/astrubale/Progetti/CompilerMinecraftQt/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/astrubale/Progetti/CompilerMinecraftQt -I/home/astrubale/Progetti/CompilerMinecraftQt -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtXml -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/ui/TypeSelectionDialog.h -o build/moc/moc_TypeSelectionDialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/obj/main.o: src/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/main.o src/main.cpp

build/obj/Block.o: src/logic/Block.cpp src/logic/Block.h \
		src/logic/MinecraftObj.h \
		src/logic/MinecraftObjVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Block.o src/logic/Block.cpp

build/obj/Item.o: src/logic/Item.cpp src/logic/Item.h \
		src/logic/MinecraftObj.h \
		src/logic/MinecraftObjVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Item.o src/logic/Item.cpp

build/obj/JsonHandler.o: src/logic/JsonHandler.cpp src/logic/JsonHandler.h \
		src/logic/Item.h \
		src/logic/MinecraftObj.h \
		src/logic/Material.h \
		src/logic/Weapon.h \
		src/logic/Block.h \
		src/logic/LightBlock.h \
		src/logic/OreBlock.h \
		src/logic/JsonVisitor.h \
		src/logic/MinecraftObjVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/JsonHandler.o src/logic/JsonHandler.cpp

build/obj/JsonVisitor.o: src/logic/JsonVisitor.cpp src/logic/JsonVisitor.h \
		src/logic/MinecraftObjVisitor.h \
		src/logic/Item.h \
		src/logic/MinecraftObj.h \
		src/logic/Material.h \
		src/logic/Weapon.h \
		src/logic/Block.h \
		src/logic/OreBlock.h \
		src/logic/LightBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/JsonVisitor.o src/logic/JsonVisitor.cpp

build/obj/LibraryManager.o: src/logic/LibraryManager.cpp src/logic/LibraryManager.h \
		src/logic/MinecraftObj.h \
		src/logic/Material.h \
		src/logic/Item.h \
		src/logic/JsonHandler.h \
		src/logic/XmlHandler.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/LibraryManager.o src/logic/LibraryManager.cpp

build/obj/LightBlock.o: src/logic/LightBlock.cpp src/logic/LightBlock.h \
		src/logic/Block.h \
		src/logic/MinecraftObj.h \
		src/logic/MinecraftObjVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/LightBlock.o src/logic/LightBlock.cpp

build/obj/Material.o: src/logic/Material.cpp src/logic/Material.h \
		src/logic/Item.h \
		src/logic/MinecraftObj.h \
		src/logic/MinecraftObjVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Material.o src/logic/Material.cpp

build/obj/MinecraftObj.o: src/logic/MinecraftObj.cpp src/logic/MinecraftObj.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/MinecraftObj.o src/logic/MinecraftObj.cpp

build/obj/ObjectFactory.o: src/logic/ObjectFactory.cpp src/logic/ObjectFactory.h \
		src/logic/MinecraftObj.h \
		src/logic/Item.h \
		src/logic/Block.h \
		src/logic/OreBlock.h \
		src/logic/Material.h \
		src/logic/LightBlock.h \
		src/logic/Weapon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/ObjectFactory.o src/logic/ObjectFactory.cpp

build/obj/OreBlock.o: src/logic/OreBlock.cpp src/logic/OreBlock.h \
		src/logic/Block.h \
		src/logic/MinecraftObj.h \
		src/logic/Material.h \
		src/logic/Item.h \
		src/logic/MinecraftObjVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/OreBlock.o src/logic/OreBlock.cpp

build/obj/Weapon.o: src/logic/Weapon.cpp src/logic/Weapon.h \
		src/logic/Item.h \
		src/logic/MinecraftObj.h \
		src/logic/Material.h \
		src/logic/MinecraftObjVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Weapon.o src/logic/Weapon.cpp

build/obj/XmlHandler.o: src/logic/XmlHandler.cpp src/logic/XmlHandler.h \
		src/logic/MinecraftObj.h \
		src/logic/Item.h \
		src/logic/Material.h \
		src/logic/Weapon.h \
		src/logic/Block.h \
		src/logic/LightBlock.h \
		src/logic/OreBlock.h \
		src/logic/XmlVisitor.h \
		src/logic/MinecraftObjVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/XmlHandler.o src/logic/XmlHandler.cpp

build/obj/XmlVisitor.o: src/logic/XmlVisitor.cpp src/logic/XmlVisitor.h \
		src/logic/MinecraftObjVisitor.h \
		src/logic/Item.h \
		src/logic/MinecraftObj.h \
		src/logic/Material.h \
		src/logic/Weapon.h \
		src/logic/Block.h \
		src/logic/OreBlock.h \
		src/logic/LightBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/XmlVisitor.o src/logic/XmlVisitor.cpp

build/obj/CardVisitor.o: src/ui/CardVisitor.cpp src/ui/CardVisitor.h \
		src/logic/MinecraftObjVisitor.h \
		src/logic/Item.h \
		src/logic/MinecraftObj.h \
		src/logic/Weapon.h \
		src/logic/Material.h \
		src/logic/Block.h \
		src/logic/LightBlock.h \
		src/logic/OreBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/CardVisitor.o src/ui/CardVisitor.cpp

build/obj/FormVisitor.o: src/ui/FormVisitor.cpp src/ui/FormVisitor.h \
		src/logic/MinecraftObjVisitor.h \
		src/logic/MinecraftObj.h \
		src/logic/Item.h \
		src/logic/Weapon.h \
		src/logic/Material.h \
		src/logic/Block.h \
		src/logic/LightBlock.h \
		src/logic/OreBlock.h \
		src/logic/LibraryManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/FormVisitor.o src/ui/FormVisitor.cpp

build/obj/ListView.o: src/ui/ListView.cpp src/ui/ListView.h \
		src/logic/MinecraftObj.h \
		src/logic/LibraryManager.h \
		src/logic/Material.h \
		src/logic/Item.h \
		src/ui/CardVisitor.h \
		src/logic/MinecraftObjVisitor.h \
		src/ui/TypeSelectionDialog.h \
		src/logic/ObjectFactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/ListView.o src/ui/ListView.cpp

build/obj/MainWindow.o: src/ui/MainWindow.cpp src/ui/MainWindow.h \
		src/ui/ListView.h \
		src/logic/MinecraftObj.h \
		src/ui/FormVisitor.h \
		src/logic/MinecraftObjVisitor.h \
		src/logic/LibraryManager.h \
		src/logic/Material.h \
		src/logic/Item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/MainWindow.o src/ui/MainWindow.cpp

build/obj/TypeSelectionDialog.o: src/ui/TypeSelectionDialog.cpp src/ui/TypeSelectionDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/TypeSelectionDialog.o src/ui/TypeSelectionDialog.cpp

build/obj/moc_FormVisitor.o: build/moc/moc_FormVisitor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_FormVisitor.o build/moc/moc_FormVisitor.cpp

build/obj/moc_ListView.o: build/moc/moc_ListView.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_ListView.o build/moc/moc_ListView.cpp

build/obj/moc_MainWindow.o: build/moc/moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_MainWindow.o build/moc/moc_MainWindow.cpp

build/obj/moc_TypeSelectionDialog.o: build/moc/moc_TypeSelectionDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_TypeSelectionDialog.o build/moc/moc_TypeSelectionDialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

